export type CompanySuggestion = { name: string; ticker: string };

export const COMPANY_SUGGESTIONS: CompanySuggestion[] = [
  { name: "Apple", ticker: "AAPL" },
  { name: "Microsoft", ticker: "MSFT" },
  { name: "Alphabet", ticker: "GOOGL" },
  { name: "Amazon", ticker: "AMZN" },
  { name: "Meta", ticker: "META" },
  { name: "Tesla", ticker: "TSLA" },
  { name: "Nvidia", ticker: "NVDA" },
  { name: "Netflix", ticker: "NFLX" },
  { name: "Salesforce", ticker: "CRM" },
  { name: "Adobe", ticker: "ADBE" },
  { name: "Intel", ticker: "INTC" },
  { name: "AMD", ticker: "AMD" },
  { name: "Qualcomm", ticker: "QCOM" },
  { name: "Broadcom", ticker: "AVGO" },
  { name: "Oracle", ticker: "ORCL" },
  { name: "IBM", ticker: "IBM" },
  { name: "Cisco", ticker: "CSCO" },
  { name: "PayPal", ticker: "PYPL" },
  { name: "Shopify", ticker: "SHOP" },
  { name: "Zoom", ticker: "ZM" },
  { name: "Spotify", ticker: "SPOT" },
  { name: "Uber", ticker: "UBER" },
  { name: "Lyft", ticker: "LYFT" },
  { name: "Airbnb", ticker: "ABNB" },
  { name: "DoorDash", ticker: "DASH" },
  { name: "Snap", ticker: "SNAP" },
  { name: "Pinterest", ticker: "PINS" },
  { name: "Robinhood", ticker: "HOOD" },
  { name: "Coinbase", ticker: "COIN" },
  { name: "JPMorgan Chase", ticker: "JPM" },
  { name: "Goldman Sachs", ticker: "GS" },
  { name: "Morgan Stanley", ticker: "MS" },
  { name: "Bank of America", ticker: "BAC" },
  { name: "Visa", ticker: "V" },
  { name: "Mastercard", ticker: "MA" },
  { name: "American Express", ticker: "AXP" },
  { name: "Johnson & Johnson", ticker: "JNJ" },
  { name: "Pfizer", ticker: "PFE" },
  { name: "Moderna", ticker: "MRNA" },
  { name: "UnitedHealth", ticker: "UNH" },
  { name: "Walmart", ticker: "WMT" },
  { name: "Target", ticker: "TGT" },
  { name: "Costco", ticker: "COST" },
  { name: "Nike", ticker: "NKE" },
  { name: "Starbucks", ticker: "SBUX" },
  { name: "McDonald's", ticker: "MCD" },
  { name: "Disney", ticker: "DIS" },
  { name: "Comcast", ticker: "CMCSA" },
  { name: "Verizon", ticker: "VZ" },
  { name: "AT&T", ticker: "T" },
  { name: "Exxon Mobil", ticker: "XOM" },
  { name: "Chevron", ticker: "CVX" },
  { name: "Boeing", ticker: "BA" },
  { name: "Lockheed Martin", ticker: "LMT" },
  { name: "General Electric", ticker: "GE" },
  { name: "Ford", ticker: "F" },
  { name: "General Motors", ticker: "GM" },
  { name: "Rivian", ticker: "RIVN" },
  { name: "Lucid", ticker: "LCID" },
  { name: "Palantir", ticker: "PLTR" },
  { name: "Snowflake", ticker: "SNOW" },
  { name: "MongoDB", ticker: "MDB" },
  { name: "Datadog", ticker: "DDOG" },
  { name: "Cloudflare", ticker: "NET" },
  { name: "CrowdStrike", ticker: "CRWD" },
  { name: "Palo Alto Networks", ticker: "PANW" },
  { name: "Fortinet", ticker: "FTNT" },
  { name: "ServiceNow", ticker: "NOW" },
  { name: "Workday", ticker: "WDAY" },
  { name: "HubSpot", ticker: "HUBS" },
  { name: "Twilio", ticker: "TWLO" },
  { name: "Block", ticker: "SQ" },
  { name: "Intuit", ticker: "INTU" },
  { name: "Autodesk", ticker: "ADSK" },
  { name: "Synopsys", ticker: "SNPS" },
  { name: "ASML", ticker: "ASML" },
  { name: "Taiwan Semiconductor", ticker: "TSM" },
  { name: "Samsung", ticker: "SSNLF" },
  { name: "Sony", ticker: "SONY" },
  { name: "Toyota", ticker: "TM" },
  { name: "Shell", ticker: "SHEL" },
  { name: "LVMH", ticker: "LVMUY" },
];

export function filterSuggestions(query: string, limit = 8): CompanySuggestion[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return COMPANY_SUGGESTIONS.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.ticker.toLowerCase().includes(q)
  ).slice(0, limit);
}
