import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        surface: "#0b1326",
        "on-primary": "#003737",
        "secondary-container": "#4a8eff",
        "tertiary-container": "#a96039",
        "surface-tint": "#76d6d5",
        "outline-variant": "#3e4949",
        "primary-fixed": "#93f2f2",
        "on-secondary-container": "#00285b",
        "surface-variant": "#2d3449",
        "on-tertiary-fixed-variant": "#733512",
        tertiary: "#ffb692",
        "on-background": "#dae2fd",
        secondary: "#adc7ff",
        "primary-fixed-dim": "#76d6d5",
        "on-surface-variant": "#bdc9c8",
        error: "#ffb4ab",
        "inverse-surface": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "on-secondary-fixed": "#001a41",
        "tertiary-fixed-dim": "#ffb692",
        "on-error": "#690005",
        primary: "#76d6d5",
        "inverse-primary": "#006a6a",
        "surface-container-low": "#131b2e",
        "on-primary-fixed": "#002020",
        "surface-container-highest": "#2d3449",
        "on-secondary": "#002e68",
        "primary-container": "#008080",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdbcb",
        "surface-container-high": "#222a3d",
        "on-tertiary-fixed": "#341100",
        "on-surface": "#dae2fd",
        "on-tertiary": "#552000",
        outline: "#879392",
        "inverse-on-surface": "#283044",
        "secondary-fixed": "#d8e2ff",
        "surface-container": "#171f33",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#e3fffe",
        "on-secondary-fixed-variant": "#004493",
        "on-tertiary-container": "#fff9f7",
        "on-primary-fixed-variant": "#004f4f",
        "secondary-fixed-dim": "#adc7ff",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
      },
      borderRadius: {
        DEFAULT: "0.375rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
